name: Node.js CI/CD Pipeline

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Start Docker Compose
        run: docker compose up -d --build


      - name: Show running containers
        run: docker ps


      - name: Show containers logs
        run: docker compose logs --no-color


      - name: Wait for API
        run: |
          echo "⏳ Waiting for API..."

          timeout 60 bash -c '
          until curl -f http://localhost:3000/users > /dev/null; do
            echo "Still waiting..."
            sleep 2
          done
          '

          echo "✅ API is available!"


      - name: Run Tests
        run: npm test


      - name: Show logs if failed
        if: failure()
        run: docker compose logs --no-color